name: Team Peoli App CI

on:
  push:
    branches: ["main"]

env:
  EXPO_PUBLIC_API_URL: https://api.teampeoli.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Clean previous builds
        run: rm -rf dist .expo

      - name: Build web application
        run: |
          EXPO_PUBLIC_API_URL=${{ env.EXPO_PUBLIC_API_URL }} \
          EXPO_PUBLIC_VAPID_PUBLIC_KEY=${{ secrets.EXPO_PUBLIC_VAPID_PUBLIC_KEY }} \
          npx expo export -p web
        
      - name: Prepare server for new files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: rm -rf /home/${{ secrets.USERNAME }}/webapp

      - name: Copy built files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "dist"
          target: /home/${{ secrets.USERNAME }}/webapp
